language: python
python: 3.6.7
install:
  - python wsgi.py -q install
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
env:
  - DJANGO_VERSION=2.2.7
script:
  - pytest
deploy:
  provider: heroku
  api_key:
    secure: ZVQUrpsjiGivkBcH3yLZYS7W/98SktwY2/K4/XenZs1xam/QHykEYO3ETNkY4lD4FlhYfJ3ZIK/vG1uAYOrioNkOJ3iY2lRpRtatc7xgfKzfF7vo5QD9d+o9zVVHA6meKMOtXVHPug/5C0lNvEtQSXiKSRuhlLHAJgMGJD0pE1StIh4x7I1TLbATWmDTwE/00y92NyF0fRMarEcocXxkgLznsnVjwAA8cZL8GJ2vLFkrep/SltiLkSwJO5gtyKPV9cyPnA8D4dEbaqX4+UwW9F9Injy05XGyNENmcipbgr7uyP7NIu6EjCej7SHbcGxXzIu4bCpbY/C/wlk6UXj2EYG+snfVO8pQdUojUonoOzyKdj99FL2YKgx+MwETcMBBAr8lDc3FOKarqkmZKaodPb9PHGNr97w+6y5S8aRNTdsUdxSLbx38Ly+wMk9ZVmD70MdPbu9H1vPddPzMA1RyJrPjj8vFkVG3I8X6YOCpJf2pImiu4gXjYMuTUVboSGut4V+iwL+VGP1AnSYDkYH/SxkuIfF2kRl0vya3e5IgkusfM6QWslX/Y0OGXeROnBvNuVo2UkM0H0P0pYz/waTpd4SO8Hym2WvvBA+nW4+QC7ThjB7Zg/c79mhfdwoaW2SaSWPvl6AcJkWnowspWe2R6V3GMxfMDix2A/wkeIMPt0c=
  app: lab11111
