language: python
python: 3.6.7
deploy:
  provider: heroku
  api_key:
    secure: kPOeKsWNNOsfFDV4KkN+x7xdLB74liwaOYNHmlbPLeI9sxmy+CyKF8kgvHsSFV3G6uNXDRBb6H8lGdZcIcos6aBJ+zbB4Lly0gIHZnIPupg8qkBLGKPDy/B79I/jRLeK+XvB4A9SADt204B61t9XJQ/1Z7vfioKlVxelM5GBaSlPTutKuRlVB1m7aiv1COYPFZC9xlaAfbr/yv4wW56XknUSn/awLIOnd9PIDlVeGkxjfrM7IUtcN8LiWrB524go7uhCCUXV9U9rQHAMziQkdXW35Z/MvRnTe4Smk5eG45vfRftMOYYW/Hh+U6dqhXTUFj6UDtwLQEOlr+JSK4Jv0FeP0/73GEfEtZoaBRX3Mq+ZvFzBRbcCl/aWjQn6YfLTd67OiEvaBjbt2hCLpn5/YsN1usZcoLT+drwBvfztBb0S7nIcYc1vaIMSG0QHfF0J7DyYuyLoRsJ7TXJNt23DbnaXyKrRE0jBTXMqwue15/SwAoVmstEjSXyAcASP2d6NrYHWxXvXI0HBKSp/elaRLFy+T/CPPibUC49aRtCNjC1aLekAFuvDFQHkjOq7L0SSfHKaUM3Slu1u7rf3qIGP3++gf5VETU1TKuOsx/PriAXxVHfZ2VMHRMj+JQ4Q9+esptdLR0nS+tvxAJpOjHOZ78KV10bdthjESFnbKQuRMq4=
  app: lab11111
