language: python
python: 3.6.7
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
env:
  - DJANGO_VERSION=2.2.7
script:
  - pytest
deploy:
  provider: heroku
  api_key:
    secure: go95MUV+woRKtGYsn3/GKGNB6kpOpyh55+7lCGKfDWpgXAb7Fg/q3E9f7krU9F1uG4NbeaSFGV9++ZDUzRx1/0MhJP3n5dEPTN3Tw0UPYUgxXcKiAsqjBgPQoYUtS8CZ6yXpOOIhzjjLjOq2G4U4t6fKCrXYXKFHg870rmRlQuxsB5PoWBx8VjrwS7QHP4Slxr/u1OXCvrEKOAhG6mh+OW03CJsMOCjvnIj4Rv5wqAQcXz1dNLZkKaIyMEZTgigocx5Pauf8nbtN04iITmT8cBl8frOQ6ar0wSDtzMgIi725nJM4uBEe+Vayhba9R8jG2m6W+LjiDG9E4FiUnxTJP1ou4nxMuSGlIvQNO1RXYLNeDiu8nX9zvo028a0dbCxAVoMzxpQHzyLivNSRo1Nf41S8hIwybWqgV+jS0y1DVf2I/KvxwD81MyIPjU3QKeFActzD5b9nBmnEt07XzODGeezUVuhzIBXqx4cyHbpE1fwPPy/Yaj1FBLEDqH4I3Y8m/n3mrJuHuA8o2J31OZfcE9iz5mEHTfjNonOhMpAhQZwn0YqkVWhR+WtiUaBar7rnDjE/zeaZvhRhp7LCVW5FX50M/Rhd94WQaYTE8Pa5yyBxtwcXMm8/wK0Pk1NIDVIMrG/jrCdOv6J5tdE9Fojn/GkSTbSL1EeJLdgylGw/YIE=
  app: lab11111
