language: python
python: 3.6.7
install: "-pip install -r requirements.txt"
deploy:
  provider: heroku
  api_key:
    secure: emGwLXu1QMaEluxycSOljpBL6zckdEwjuM6W2/vB/NS47oyo7ugoVI87ZxDoxDFF7WPMvpYbUq4aY49ZioKlegTpWhMFBXhV0iHpTa4js22fGVL168IyvkdCj1RHKixzYxQ7Yc+4T4MkN4dcB3/ZIfSn/LDWSrTWf4zqCPma5drsayh372IR8L2kRDB/3BdhYqxGUmqK5adeC5HHr5qAeyFmsBZqeMCGRu87a1eC0OsBelUnKrU+zvJlKTZILTjaYw4TWxCjRCbP/OyGkhdGEEPgUcTXprhrQXKW4eofYPhjlkGIRCWRzwckwmx320J0v8IXBvjRLDH5e1fSEaSUWytJEU1+0N6rWJxq7/OBuehqNrfrlQ9zmyFVXi74tvwwstIPJqb7i7b/mfBsehoKfVcjHkXkit5WS3DMj0nY+5h303J5gH6CsYnTpxTPCjH+PWVSY3n+AQPCCR68Ru2raDVUKYVCXGyFe2oeHnWYmqWcaJpy/g9VDs59pTeux71FTf8YSm5bNmGaYawsXV9t59YEjgWbSchh9lpu6HG9dre7xfRt2YpNMNEEoG8CLvG8udqR3gtXBG0HL6nHegGMwk/wapjXBq+4M1Xwp331cnLiz1O2GKQnF6/8zJ3iMWD2S7Rihitun2NW/xQ/mfgbtcOeUyGGbzS5D329OvsV5aE=
  app: lab11111
