language: python
python: 
  "3.6.7"
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
env:
  - DJANGO_VERSION=2.2.7
script: make test
deploy:
  provider: heroku
  api_key:
    secure: YhGLlzgsr3mGpkSFTSqMKjkiKt41s+6VTx3lmNJqJEh8AOXDeNjQJC6rJjrbKs+cgDd+JdapRHoicqB7ZAhqB2Axn1ZTq0qke+ve0C6iHCP6CPkuyZEmiDu8rV1EF0fiyYRVb6TDFiLEoGR9uHEjY1aUAXZwHknnU6bxKx+6cnp2t/UFhNsolpIiQqFcWvVDNEpqBqWq2xIy6QRNFd780yqQ6CUJXwBu1I6l1rDBNSxXUOh5b0xJyqcWRjgQnVm8DV7grgkqgr0la23g94rKFVfO8W1eXWA9n+If3E5gD1kpi4rW78NUBsdPYgBJUZDc1CNZMLyLZWnhwQ7YOP7qp7RSk7mopi4368RkfynegKmv8QwSTfx9umb0aNoYkJ2jBbNK6i0FO146Jl/y0eJnqwVytI0agfWN44gHiKzw0/EIEOyHuf/AjhsQtQUx3csotRXEZM77OwXirpwaHtlMU86yMXND/EHq7gODycnrxDGuVCCKSGpd10QlXtWpIT7ULb/Vk1xWFLrNyZqysRUMT4zBD5JCV7b+WytPZBhLpvnXvZG6iX8Ew82v0AxEyv/dGHF2qapIjtp6KvkZQIhnTEvBr4OnURV5KAEoJISUowsz+B8uWef4mzbqQ2fc21hfJ9vqofyTX6Ge5cIJzXADt1v1+OC6RjgkKXvfWo8IVYU=
  app: lab11111
