language: python
python: 
  "3.6.7"
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
script:
  - python manage.py test 
env:
  - DJANGO_VERSION=1.8.5
deploy:
  provider: heroku
  api_key:
    secure: p2+k2y5ApAAOGpjJXx9Gxa3ojrVgS4nYcU4ASNwy4J6Lcv0ZoG6LP5K4sNADeQnvtBHG+TVLF0ZLba2j74o065gqKXlnHglvxpeKsHfTk42MitxSTz1kGMj4YYEsbVzU2qNjhGPHK0caDUAgkFTIqydMPSLOicGI6g9ezZD8ZAPhbwzTgbJTKo+6SSAji3O3wwwwPdNeWdMxotbGoLrMOI7QY75bE6dkl0fOgbZjZEqshCcXzG/j5/B/x8gkCNxSDpEtpty4sRbIPt6hN8lSmf92adPVcI7ZGKwOiSOYOwZyWQfizAWE8Sh+xriS9Rx+RdeCqBc0dQSDuEt9J/XmCgds5/0qMI0O/vVdNRXhFzMkZWX4C2mo+0D7k5O+gxjWW0uVnWmafLN875yccL7+M9VBh4CxB1v+AkrAMp2OKlw+owdRAF8VSq+d+VLU27R3q+CX8QxXNOHjQgpZdEsEU8oqAbdqMoLjvss9+MKkOqmAICIGiqX/fHOf0lEb3JgHewM5IzE/56201miQu9GJ46baaJRL3uGztDAV6MBQB1u9IRst2+n8Mgt97XyqFnCsq5EXz/P2dinEorTGLlIu9raE8HdOfMUZFhAo6Pzv8Bj0p/L5l28AyTofLszGZfntNlk9cUKHIlWm3oSQEuxcT0P5ON5P5XTAtNlUpQnMykI=
  app: lab11111
