language: python
python: 3.6.7
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
env:
  - DJANGO_VERSION=2.2.7
deploy:
  provider: heroku
  api_key:
    secure: dwbVdjcnnwmbY26QoOdLazPKhKAN9D9Di93y9MZbl1tCdnSqT6tx14CkR4Ah8ykx4ZPHzWHh7gY7Zeol/Hs6VrAe1wu7ilouU3HbhbWmjYq/ngFPsbmuHuoF6dgj0+kYH6069dLWW3U904p4jNibtqgGEw0l6tPGxqt52ZLzCL4shAJjhanaHh9mt+4S1qyAFgPvt6agm+LerQEASYuPdNsLe1hRfsZAjLPc1kShcDnAyOZgierwijnBq9/Uy13aoLhaR5nF/aZr5BIpPhvkpVEe9tNM/s8Ph7M5vFic6z6BsT3ihvmAnylPYDvgc4LkFIpMQbZiAkrGWcidvHqEZo59NauvpZyT+g7+YPZ1C9paT9HQ2RSSFmUIvqZFW0q9TL2tj2YHxunVdTv3fzpsEBQmvUYv715F7SmlhhPX+zC/xT6CAXiLwkb2lc6B7qOv9Y9jEO1JMFtLGinuXkJENlNIGgZLbqf6S43dqTxmq3H5U8ijT6uYTcYADIj5eyx58k0HQBWEfBeIlY506TLhuslrKTxoQcuNJb1FLSni9kGvET5UInCnNYTjFK1mIC5ptMrbRqNKmjtYATGanFNTArT44XE6ETnA0rnardXPXcTSMYRybH3Fl2PIlascgOMlWRONkHyvaxE2yynwglo9Us8z/wudNjoLgBS3opTMuyY=
  app: lab11111
