language: python
python: 3.6.7
install: "-pip3 install -r requirements.txt"
deploy:
  provider: heroku
  api_key:
    secure: RKBCh71rHmzgLwyymGJpgDGiAR51MkjjCkHP50VQ8cBCW7TqsFokvQD96xJzqqIiDOUWKdA/RTdTqGUq3UImtHkS0cozggfQeWCvHxGtUdpR9XjdcqFOxVUfktKxmNo0nfSi50hRzkJKi+Ak9QS5j5yvRdziApfabsXLtHvtjczMDZuZspKvIP0AlITx6zSyMkVm5QINrHNOdrZW9lBA7MDgFla//qecV27ObRmYBgUzjG8aznNQQMWJCsLlMvsVrdtUMFxI87QO24QH7ITzWTcmO4HbF/a9aUk4/qknQkeeguMuuEZ0EAXApYWGFbczwHUoBU5TbKeDJAgdkzJ2mFOJp9nje8TOrv5V16T/0X6btKblJxAtMVrfL4VJHbjEFZiCm6OLwvGgQ2LmTsFH6S8fHdq9mEOEBhNQIzHI/vCniux/mBgIbRZXKLCY2qdFmu4KvC1nJAKVLpADb5xvPVYfrHFlntgfbeSjuDvPaj+SXszLtW/Hs0skdPl4zzw3vBQrfR8Ccj9akpbwpfexkzU96f8jutN2AmFqxsV2QrD4Bv6lw5FgN9sNKlVk85OKN1QTg5wvl/MuNx6OhW7dJI21l8315TQQTZlrxcTsGgv9vajHGq37JW/9huP5RYuvny583y8WivvDS+GO//GobGFo9pHDMBtBadQpB3054Ds=
  app: lab11111
