language: python
python: 3.6.7
deploy:
  provider: heroku
  api_key:
    secure: pswejFkEsW/hAYicQNFSTKmZS8kN+2A49Tk9F98YR/WS3f6t4eYxMYigB4IJg4vBzbsP4PLIgHfazJY+66qGqiTdCLqG3G5aI6gYRvxZHtgshDvXkuk4o0I3YxBjyyHnwhNy70b+3VCon8M5UlDlOcnPgilKtUdPyUG39mkoA+cIjaoq+KWHZCFXCQR9u4Fzsm63wmYsu9T9+c0xKNp5jAuu7N2t89ZGZWHSGp//L9XMqBI8tbAl63/dB1Y4y/AlVzYjLVQWLjKL2S/nzfT0dYUvESrn2XGc60y8AmFfHIIux8wsAbwy5L0QTpJdtIYU1ZXnUN/XLfa1NYxeZHMAV3m9q/JGhxnXsazEL/VHptmW/Ar0yi5cj44KEYhDAI/ZzgbrfFhjgTfY7TR16xbm5H/8fMTDKjY1bE8jGh58I8XmPUt1tESNNB7r1AmPyw1wOA5fr6gAHeTx2Z5BsAZ5KMhWpYpSjUy9l93oDlueS5/Zol3VO0BcHLyhMDWrTwqngjI9+ftbZUA1ekiBNEE5BtEaF0PSOwruH02kWx4UACjf3iefYTujB0EsdQk8863egE6qXJGt9Rv4gZE2M9jq5SkNZthTMAzaHMODBtgVUwSAHvEf7PIz2a79ZVTYaUGMyVKQGnTwkIcqAl3Csvw3UCGa1n29JELFTCBzW9nFyic=
  app: lab11111
